### ISSUE TITLE
cross fails with targets aarch64-unknown-linux-musl and x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by ddeguglielmo** [sifis-home/dht-to-mqtt#2]
Cross fails reporting the following errors:

error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> /home/domenico/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.1.16/src/util_libc.rs:113:14
    |
113 |     let fd = open(path.as_ptr() as *const _, libc::O_RDONLY | libc::O_CLOEXEC);
    |              ^^^^------------------------------------------------------------- an argument of type `u32` is missing
    |
note: function defined here
   --> /home/domenico/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.145/src/unix/linux_like/linux/musl/lfs64.rs:112:26
    |
112 | pub unsafe extern "C" fn open64(
    |                          ^^^^^^
help: provide the argument
    |
113 |     let fd = open(path.as_ptr() as *const _, libc::O_RDONLY | libc::O_CLOEXEC, /* u32 */);
    |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lu-zero** [comment]
The root problem is rust-1.70.0 sporting a musl 1.2, upstream issue for getrandom https://github.com/rust-random/getrandom/issues/363.

I'm testing how hard is to tell `cross` to use rust-1.69.0, if it works we can use it as workaround meanwhile.

**Comment by lu-zero** [comment]
The problem is actually `libc-0.2.145`.
